server:
  port: 9090

spring:
  application:
    name: EatSmart API
  datasource:
    url: jdbc:postgresql://localhost:1111/postgres
    username: qwe
    password: qwe
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:db/changelog/master.yml
  h2:
    console:
      enabled: false
  jpa:
    hibernate:
      ddl-auto: validate
