server:
  port: 9090

spring:
  application:
    name: EatSmart API
  datasource:
    url: jdbc:postgresql://db:5432/postgres
    username: qwe
    password: qwe
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:db/changelog/master.yml
  jpa:
    hibernate:
      ddl-auto: validate
logging:
  file:
    name: logs/app.log
  level:
    root: INFO
    org.springframework: INFO
    com.zaxxer.hikari: ERROR
    liquibase: ERROR
    org.springframework.security: ERROR
  logback:
    rolling policy:
      max-history: 5
      max-file-size: 10MB
